//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fmRadio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fmRadio.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add some preset.
        /// </summary>
        public static string AddSomePreset {
            get {
                return ResourceManager.GetString("AddSomePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This frequency has already been saved..
        /// </summary>
        public static string AlreadySavedFrequencyError {
            get {
                return ResourceManager.GetString("AlreadySavedFrequencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fmRadio.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between.
        /// </summary>
        public static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Bug fixes.
        /// </summary>
        public static string BugFix {
            get {
                return ResourceManager.GetString("BugFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t tune into that frequency in your region!.
        /// </summary>
        public static string CantTuneIntoThatFrequencyInYourRegion {
            get {
                return ResourceManager.GetString("CantTuneIntoThatFrequencyInYourRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change FM Radio region.
        /// </summary>
        public static string ChangeFmRadioRegion {
            get {
                return ResourceManager.GetString("ChangeFmRadioRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change the FM Radio region for the app from settings page.
        /// </summary>
        public static string ChangeFmRadioRegionDesc {
            get {
                return ResourceManager.GetString("ChangeFmRadioRegionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change log.
        /// </summary>
        public static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and developed by.
        /// </summary>
        public static string DesignedAndDevelopedBy {
            get {
                return ResourceManager.GetString("DesignedAndDevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directly tune info a custom frequency.
        /// </summary>
        public static string DirectlyTuneInfoACustomFrequency {
            get {
                return ResourceManager.GetString("DirectlyTuneInfoACustomFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can access the frequency input page by tapping on the current frequency indicator.
        /// </summary>
        public static string DirectlyTuneInfoACustomFrequencyDesc {
            get {
                return ResourceManager.GetString("DirectlyTuneInfoACustomFrequencyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donate/buy the app.
        /// </summary>
        public static string DonateOrBuy {
            get {
                return ResourceManager.GetString("DonateOrBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback email.
        /// </summary>
        public static string FeedbackEmail {
            get {
                return ResourceManager.GetString("FeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fmRadio App v.
        /// </summary>
        public static string FmRadioAppV {
            get {
                return ResourceManager.GetString("FmRadioAppV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM radio region.
        /// </summary>
        public static string FmRadioRegion {
            get {
                return ResourceManager.GetString("FmRadioRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the frequency can&apos;t be empty..
        /// </summary>
        public static string FrequencyCantBeEmpty {
            get {
                return ResourceManager.GetString("FrequencyCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency out of bounds.
        /// </summary>
        public static string FrequencyOutOfBounds {
            get {
                return ResourceManager.GetString("FrequencyOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something wrong happened while saving your preset. Re-launching the app may help..
        /// </summary>
        public static string FrequencySaveError {
            get {
                return ResourceManager.GetString("FrequencySaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how-to.
        /// </summary>
        public static string HowTo {
            get {
                return ResourceManager.GetString("HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageSetting {
            get {
                return ResourceManager.GetString("LanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Minor bug fixes.
        /// </summary>
        public static string MinorBugFix {
            get {
                return ResourceManager.GetString("MinorBugFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value!.
        /// </summary>
        public static string MissingValue {
            get {
                return ResourceManager.GetString("MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name your preset.
        /// </summary>
        public static string NameYourPreset {
            get {
                return ResourceManager.GetString("NameYourPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Antenna.
        /// </summary>
        public static string NoAntenna {
            get {
                return ResourceManager.GetString("NoAntenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your headphones are used as an FM radio antenna. To listen to the radio, connect your headphones..
        /// </summary>
        public static string NoAntennaErrorMessage {
            get {
                return ResourceManager.GetString("NoAntennaErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this device doesn&apos;t support Fm Radio.
        /// </summary>
        public static string NoFmSupport {
            get {
                return ResourceManager.GetString("NoFmSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugged audio jack acts as a fm radio antenna, please plug in a headphone..
        /// </summary>
        public static string NoHeadPhoneIsPluggedError {
            get {
                return ResourceManager.GetString("NoHeadPhoneIsPluggedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North America.
        /// </summary>
        public static string NorthAmerica {
            get {
                return ResourceManager.GetString("NorthAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other apps.
        /// </summary>
        public static string OtherAppsaOfThisDeveloper {
            get {
                return ResourceManager.GetString("OtherAppsaOfThisDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate and review.
        /// </summary>
        public static string RateAndReview {
            get {
                return ResourceManager.GetString("RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this app.
        /// </summary>
        public static string RateThisApp {
            get {
                return ResourceManager.GetString("RateThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love you to rate our app 5 stars?
        ///
        ///Showing us some love on the store helps us to continue to work on the app and make things even better!.
        /// </summary>
        public static string RatingPromptBody {
            get {
                return ResourceManager.GetString("RatingPromptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate 5 stars.
        /// </summary>
        public static string RatingPromptBtn1 {
            get {
                return ResourceManager.GetString("RatingPromptBtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string RatingPromptBtn2 {
            get {
                return ResourceManager.GetString("RatingPromptBtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask again.
        /// </summary>
        public static string RatingPromptCheckBox {
            get {
                return ResourceManager.GetString("RatingPromptCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoying fmRadio?.
        /// </summary>
        public static string RatingPromptTitle {
            get {
                return ResourceManager.GetString("RatingPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove or rename a preset.
        /// </summary>
        public static string RemoveOrRenameAPreset {
            get {
                return ResourceManager.GetString("RemoveOrRenameAPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long pressing on a preset in the list will prompt you to rename or delete it.
        /// </summary>
        public static string RemoveOrRenameAPresetDesc {
            get {
                return ResourceManager.GetString("RemoveOrRenameAPresetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename or delete the preset.
        /// </summary>
        public static string RenameOrDeletePreset {
            get {
                return ResourceManager.GetString("RenameOrDeletePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save edit.
        /// </summary>
        public static string SaveEdit {
            get {
                return ResourceManager.GetString("SaveEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save/Set a preset.
        /// </summary>
        public static string SaveSetAPreset {
            get {
                return ResourceManager.GetString("SaveSetAPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like button will prompt you to name the currently playing frequency as preset.
        /// </summary>
        public static string SaveSetAPresetDesc {
            get {
                return ResourceManager.GetString("SaveSetAPresetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set new frequency.
        /// </summary>
        public static string SetNewFrequency {
            get {
                return ResourceManager.GetString("SetNewFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip through presets.
        /// </summary>
        public static string SkipThroughPresets {
            get {
                return ResourceManager.GetString("SkipThroughPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next and previous buttons will allow you to skip to a desired station/preset.
        /// </summary>
        public static string SkipThroughPresetsDesc {
            get {
                return ResourceManager.GetString("SkipThroughPresetsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened.
        /// </summary>
        public static string SomethingHappened {
            get {
                return ResourceManager.GetString("SomethingHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now
        ///Playing
        ///.
        /// </summary>
        public static string TileBackText2 {
            get {
                return ResourceManager.GetString("TileBackText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play some music.
        /// </summary>
        public static string TileText1 {
            get {
                return ResourceManager.GetString("TileText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing.
        /// </summary>
        public static string TileText2 {
            get {
                return ResourceManager.GetString("TileText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now this is a serious problem. :( Report this please..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreachable value!.
        /// </summary>
        public static string UnreachableValue {
            get {
                return ResourceManager.GetString("UnreachableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Minor bug fixes.
        /// </summary>
        public static string V101Desc {
            get {
                return ResourceManager.GetString("V101Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Minor bug fixes.
        /// </summary>
        public static string V102Desc {
            get {
                return ResourceManager.GetString("V102Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Reminder for rating and reviewing.
        /// </summary>
        public static string V103Desc {
            get {
                return ResourceManager.GetString("V103Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Fix for North America region tuner, now displaying odd numbers only.
        /// </summary>
        public static string V105Desc1 {
            get {
                return ResourceManager.GetString("V105Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Bug fixes.
        /// </summary>
        public static string V105Desc2 {
            get {
                return ResourceManager.GetString("V105Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Bug fix for frequency indicator.
        /// </summary>
        public static string V106Desc {
            get {
                return ResourceManager.GetString("V106Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Initial version.
        /// </summary>
        public static string V10Desc {
            get {
                return ResourceManager.GetString("V10Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Added in-app purchase option to support development.
        /// </summary>
        public static string V110Desc1 {
            get {
                return ResourceManager.GetString("V110Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - New Turkish language support.
        /// </summary>
        public static string V110Desc2 {
            get {
                return ResourceManager.GetString("V110Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
